import type { AnalyticsConfidenceProfile, DatasetProfile, DatasetTypeProfile, DuplicateProfile, FieldProfile, MissingProfile, QualityProfile, RecommendedInsight } from "./types";

export function generateInsights(dataset: DatasetProfile, fields: FieldProfile[], datasetType: DatasetTypeProfile, missing: MissingProfile, duplicates: DuplicateProfile, quality: QualityProfile, confidence: AnalyticsConfidenceProfile): RecommendedInsight[] {
  const insights: RecommendedInsight[] = [
    { id: "dataset-size", title: "Dataset size", text: `This dataset contains ${dataset.totalRecords} records across ${dataset.totalFields} fields.`, severity: "info", relatedFields: [], recommendedAction: "Use this as the baseline for dashboard and report scope.", confidence: 0.98 },
    { id: "dataset-type", title: "Likely dataset type", text: `This file appears to be ${datasetType.primaryType} data. ${datasetType.reasons.join(" ")}`, severity: "info", relatedFields: [], recommendedAction: "Review the recommended visuals for this dataset type.", confidence: datasetType.confidence },
    { id: "missingness", title: "Missing-value pattern", text: `${missing.missingCells} missing cells were found across ${missing.fieldsWithBlanks} fields.`, severity: missing.missingPercent > 0.35 ? "warning" : "info", relatedFields: missing.topMissingFieldsByCount.slice(0, 5).map((field) => field.fieldName), recommendedAction: "Review high-missing fields before export or executive reporting.", confidence: 0.95 },
    { id: "duplicates", title: "Duplicate review", text: duplicates.exactDuplicateRows ? `${duplicates.exactDuplicateRows} exact duplicate rows were detected.` : "No exact duplicate rows were detected.", severity: duplicates.exactDuplicateRows ? "warning" : "opportunity", relatedFields: duplicates.likelyDuplicateRiskFields.slice(0, 5), recommendedAction: duplicates.exactDuplicateRows ? "Review duplicate groups before final outputs." : "Continue with dashboard preview and reporting.", confidence: 0.9 },
    { id: "quality", title: "Quality score", text: quality.explanation, severity: quality.overallScore < 70 ? "warning" : "info", relatedFields: fields.filter((field) => field.missingPercent > 0.25).slice(0, 5).map((field) => field.fieldName), recommendedAction: quality.recommendations[0] || "Use the quality score to prioritize cleanup.", confidence: 0.85 },
    { id: "confidence", title: "Analytics confidence", text: confidence.explanation, severity: confidence.label === "Low" ? "critical" : confidence.label === "Moderate" ? "warning" : "opportunity", relatedFields: [], recommendedAction: confidence.recommendations[0] || "Review confidence drivers before sharing conclusions.", confidence: confidence.overallConfidence / 100 }
  ];
  if (dataset.detectedDateFields.length) insights.push({ id: "date-fields", title: "Trend readiness", text: `${dataset.detectedDateFields.length} date field(s) were detected: ${dataset.detectedDateFields.slice(0, 3).join(", ")}.`, severity: "opportunity", relatedFields: dataset.detectedDateFields.slice(0, 3), recommendedAction: "Use monthly or quarterly trend visuals instead of one bar per date.", confidence: 0.85 });
  return insights;
}
