import type { DatasetProfile, DescriptiveStatsProfile, FieldProfile, MissingProfile, QualityProfile, RecommendedVisual } from "./types";

export function recommendVisuals(dataset: DatasetProfile, fields: FieldProfile[], missing: MissingProfile, quality: QualityProfile, descriptive: DescriptiveStatsProfile): RecommendedVisual[] {
  const visuals: RecommendedVisual[] = [];
  let priority = 1;
  visuals.push({ id: "quality-gauge", title: "Quality Score", description: "Overall quality with component breakdown.", type: "gauge", fieldNames: [], priority: priority++, tab: "Data Quality", packageMinimum: "Data Foundation", levelMinimum: "Essential", chartConfig: { score: quality.overallScore, components: quality.components }, insight: quality.explanation, confidence: 0.9 });
  visuals.push({ id: "missing-fields", title: "Top Missing Fields", description: "Horizontal bars showing columns with the most missing cells.", type: "horizontalBar", fieldNames: missing.topMissingFieldsByCount.map((field) => field.fieldName), priority: priority++, tab: "Data Quality", packageMinimum: "Data Foundation", levelMinimum: "Essential", chartConfig: { top: 10, groupRareValues: false }, insight: `${missing.fieldsWithBlanks} fields contain blanks.`, confidence: 0.95 });
  descriptive.date.slice(0, 3).forEach((dateField) => visuals.push({ id: `trend-${dateField.fieldName}`, title: `Records by Month: ${dateField.fieldName}`, description: "Dates are grouped by month to avoid one bar per unique date.", type: "line", fieldNames: [dateField.fieldName], priority: priority++, tab: "Visual Analytics", packageMinimum: "Management Insights", levelMinimum: "Essential", chartConfig: { grain: "month", data: dateField.recordsByMonth }, insight: `Trend view is available from ${dateField.earliest || "unknown"} to ${dateField.latest || "unknown"}.`, confidence: dateField.parseSuccessRate }));
  fields.filter((field) => field.chartable && field.type === "categorical").slice(0, 5).forEach((field) => visuals.push({ id: `top-${field.fieldName}`, title: `Top Categories: ${field.displayLabel}`, description: "Shows the top 5-10 categories and groups rare values as Other.", type: field.topValues.length <= 6 ? "donut" : "horizontalBar", fieldNames: [field.fieldName], priority: priority++, tab: "Visual Analytics", packageMinimum: "Management Insights", levelMinimum: "Essential", chartConfig: { top: 10, groupRareValues: true }, insight: field.topValues[0] ? `${field.topValues[0].value} is the most common value.` : "No common values were detected.", confidence: 0.8 });
  descriptive.numeric.slice(0, 4).forEach((field) => visuals.push({ id: `histogram-${field.fieldName}`, title: `Distribution: ${field.fieldName}`, description: "Histogram and outlier scan for numeric values.", type: "histogram", fieldNames: [field.fieldName], priority: priority++, tab: "Descriptive Statistics", packageMinimum: "Professional Analytics", levelMinimum: "Professional", chartConfig: { bins: 12, outlierCount: field.outlierCount }, insight: `${field.outlierCount} potential outliers detected.`, confidence: 0.75 }));
  if (dataset.detectedCategoricalFields.length) visuals.push({ id: "field-completeness", title: "Field Completeness Heatmap", description: "Completeness by field for quick data quality scanning.", type: "heatmap", fieldNames: fields.map((field) => field.fieldName), priority: priority++, tab: "Data Quality", packageMinimum: "Data Foundation", levelMinimum: "Essential", chartConfig: { metric: "completeness" }, insight: "Completeness heatmaps identify which fields are ready for reporting.", confidence: 0.85 });
  return visuals;
}
