import type { BrandingProfile, FooterModel } from "./brandingTypes";

export function buildFooter(profile: BrandingProfile, includeProgramMetricsAttribution = true): FooterModel {
  const contact = [profile.contactName, profile.contactEmail, profile.website].filter(Boolean).join(" | ") || undefined;
  return {
    organizationName: profile.organizationName,
    confidentialityLabel: profile.confidentialFooter || "Confidential",
    reportDate: profile.reportDate || new Date().toISOString().slice(0, 10),
    pageNumberPlaceholder: "Page {page} of {pages}",
    attribution: includeProgramMetricsAttribution ? "Generated by ProgramMetrics" : "",
    copyright: profile.defaultReportFooter || "Copyright (c) 2026 ProgramMetrics. All Rights Reserved.",
    contact
  };
}
